server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: example
    key-password: example
       
debug: true

spring:
  aop:
    proxy-target-class: true
  redis:
    host: docker.local
    port: 6379

zuul:
  routes:
    authserver:
      path: /authserver/**
      url: https://localhost:7777
    user:
      path: /user/**
      url: https://localhost:8443/authserver/uaa/user
    register:
      path: /register/**
      url: https://localhost:8443/authserver/uaa/register
    frontend1:
      path: /ui/**
      serviceId: frontend
      stripPrefix: false
    frontend2:
      path: /frontend/**
      serviceId: frontend

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    frontend:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon: 
  TrustStore: keystore.jks
  TrustStorePassword : example
  ReadTimeout: 60000
  IsSecure: true
  MaxAutoRetries: 1

management:
  security:
    enabled: false
security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: https://localhost:8443/authserver/uaa/oauth/token
      userAuthorizationUri: https://localhost:8443/authserver/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        id: openid
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    com.netflix.discovery: 'OFF'

---
# For deployment in Docker containers
spring:
  profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
