info:
  component: Turbine

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 8989

management:
  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

---
# For deployment in Docker containers
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
