server:
  port: 8761

management:
  security:
    enabled: false
security:
  basic:
    enabled: false

---
# For deployment in Docker containers
spring:
  profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
