server:
  host: localhost
  port: 8081
  contextPath: /ui
  use-forward-headers: true

debug: true

vaadin:
  servlet:
    params:
      productionMode: false

spring:
  aop:
    proxy-target-class: true
  redis:
    host: localhost
    port: 6379
    default_expire_time: 86400

security:
  sessions: NEVER
  basic:
    enabled: false
management:
  security:
    enabled: false

logging:
  level:
    lessor: DEBUG
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

---
# For deployment in Docker containers
spring:
  profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
