server:
  host: localhost
  port: 8081
  contextPath: /ui
  use-forward-headers: true
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: example
    key-password: example  

debug: true

vaadin:
  servlet:
    production-mode: false

spring:
  aop:
    proxy-target-class: true
  redis:
    host: docker.local
    port: 6379
    pool:
      max-wait: -1
      max-active: -1
      max-idle: -1
      min-idle: 16    

security:
  sessions: NEVER
  basic:
    enabled: false
management:
  security:
    enabled: false

logging:
  level:
    lessor: INFO
    org.springframework.security: INFO
    com.netflix.discovery: 'OFF'

---
# For deployment in Docker containers
spring:
  profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
