server:
  contextPath: /uaa
  port: 7777

email:
  username: USERNAME
  password: PASSWORD
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    auth: true
    starttls:
      enable: true

security:
  sessions: stateless
  basic:
    enabled: false

spring:
  application:
    name: authserver
  profiles:
    active: ${profile:default}
  aop:
    proxy-target-class: true
  redis:
    host: klhauser-vm1
    port: 6379
    default_expire_time: 86400
  # DataSource settings: set here your own configurations for the database
  # connection.
  datasource:
    url: jdbc:mysql://localhost:3306/microservice4vaadin_authserverdb
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    # Specify the DBMS
    database: MYSQL
    # Show or not log for each sql query
    show-sql: false
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
        # stripped before adding them to the entity manager)
        dialect: org.hibernate.dialect.MySQL5Dialect

flyway:
  enabled: false

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'
