version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.5.1
    
  mongodb:
    image: mongo:2.4

  eventstore:
    image: klhauser/microservices4vaadin-eventstore
    ports:
      - "6666:6666"
    links:
      - rabbitmq
      - mongodb
